### ISSUE TITLE
Windows installation failed.

### ISSUE THREAD

**Issue by JohnClaw** [rupeshs/fastsdcpu#7]
Screenshot of the error: 
![image](https://github.com/rupeshs/fastsdcpu/assets/131554379/b21895bd-9fee-4b6f-89dc-36fd2a8eb94f)

How can i fix it?

**Comment by rupeshs** [comment]
Which OS ?

**Comment by cubo94857** [comment]
im having this same problem i have an nvidia geforce

**Comment by rupeshs** [comment]
@cubo94857 Which operating system?

**Comment by cubo94857** [comment]
i use a windows laptop, im not a pro at this type of stuff so i hope im saying the right thing lol

**Comment by rupeshs** [comment]
@cubo94857  Which version of windows are you using (Windows 10 or Windows 11?

**Comment by cubo94857** [comment]
windows 11

**Comment by JohnClaw** [comment]
> Which OS ?

Windows 11.

**Comment by Amin456789** [comment]
it will be great if we can have a pre-installed everything for its portability, like just download it from releases and use in one go

**Comment by rupeshs** [comment]
@Amin456789  can you try reinstalling freshly downloaded repo, I have updated code

**Comment by Amin456789** [comment]
thank u for update! but in the future can we have pre-installed everything please? something like NMKD's sd, so we just extract and start to use
thanks for all ur hard work buddy

**Comment by rupeshs** [comment]
@Amin456789  Thanks, I have created a portable SD GUI https://rupeshsreeraman.itch.io/sdimagegenerator
Also NeuralStyler AI https://neuralstyler.com/

**Comment by Amin456789** [comment]
just checked it! it is great! if we can have something like that for this it will be amazing in the future!

**Comment by JohnClaw** [comment]
> can you try reinstalling freshly downloaded repo, I have updated code

It didn't help. The error remains. Screenshot:
![image](https://github.com/rupeshs/fastsdcpu/assets/131554379/6232c55a-f223-46aa-8afa-8c6d7f940ff2)

**Comment by rupeshs** [comment]
@JohnClaw Seems like your path has some issues, can you try it on another drive? 
`git clone https://github.com/rupeshs/fastsdcpu/`

**Comment by JohnClaw** [comment]
> Seems like your path has some issues, can you try it on another drive?

I have no other drive, only C:\. And all other local AI apps work fine (Easy Diffusion and Ooba Booga, for example). Please, enable unicode symbols support for paths. The problem maybe caused by non-latin characters.

**Comment by Amin456789** [comment]
@JohnClaw u should tell about this to OnnxStack too john, maybe this is like that problem, if u solve one both will be solved

**Comment by JohnClaw** [comment]
> git clone https://github.com/rupeshs/fastsdcpu/

I tried it but got the same error again: 
![image](https://github.com/rupeshs/fastsdcpu/assets/131554379/1c288011-1932-47a8-8d22-823022fdb4e4)

**Comment by cubo94857** [comment]
it worked but i am having a problem where when i try to start.bat the python coding thing will pop up for 1 second then disappear. Nothing else happens after that, is it an issue with my computer? when i double click start.bat it tells me to extract all files, so i press extract. But when i try to start it again it tells me once again to extract all files. so i just press run instead and that leads to the python coding thing popping up then disappearing.

**Comment by JohnClaw** [comment]
I also have to tell about another error. Default micromamba.exe doesn't work at all. Here's a screenshot:
![image](https://github.com/rupeshs/fastsdcpu/assets/131554379/a4cca734-69b9-42b1-adcb-0df26caca8e5)

As you can see, it downloads and installs nothing. So i replaced it with this: https://micro.mamba.pm/api/micromamba/win-64/latest

This version works better and downloads and install most of staff but crushes with the error that i described earlier in this thread.

**Comment by Amin456789** [comment]
time to a comfyui portable style package for eliminate all these errors i guess

**Comment by Amin456789** [comment]
i got that libmamba error too when i was installing cause i had a connection issue and i disconnected, but for the fix i deleted env folder so it had to recreate it make stuff in it again, it got fixed this way

**Comment by rupeshs** [comment]
@JohnClaw @cubo94857 I have removed micromamba for Windows installation in the branch https://github.com/rupeshs/fastsdcpu/tree/add-venv-install-support-windows
Please try this 
**You must have a Python installed** 
Note: pytorch does not support python 3.12 yet so make sure your python version is 3.11 or earlier.

Run these commands in a fresh folder  :

`git clone https://github.com/rupeshs/fastsdcpu/`
`git checkout branch add-venv-install-support-windows`

Double-click install.bat

**Comment by JohnClaw** [comment]
> Run these commands in a fresh folder :
> 
> `git clone https://github.com/rupeshs/fastsdcpu.git` `cd fastsdcpu` `git checkout add-venv-install-support-windows`

Thank you very much. It finally works.

**Comment by JohnClaw** [comment]
> we are doomed john haha

If the latest update doesn't help, then try this: https://huggingface.co/datasets/4eJIoBek/PAIT-Downloads/resolve/main/fastsdcpu%5Bexperimental%5Bcant%20work%20offline%5D(openvino%20only%2C%20dont%20forget%20to%20enable%20it%20in%20settings)(dreamshaperv7-distilled-into-latent-consistency-model)-portable-win.7z

**Comment by Amin456789** [comment]
yup i got that too john, but i want it to be offline so i am waiting for other options/versions to come out,
